name: Post Message

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: entepotenz/keep-github-actions-alive-min-dependencies@v1      
      - uses: oven-sh/setup-bun@v2
      - run: bun i
      - name: "execute script"
        env: 
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: bun index.ts
